### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by MarxGo** [containerops/scaffold#62]
pipeline 
- [ ] getPipelineList
- [ ] getPipelineInfo(all data in pipeline)
- [ ] createPipeline (create a new pipeline)
- [ ] createPipelineNewVersion (create a new version)
- [ ] upatePipeline (update a pipeline info)

startStage
- GitHub
 - [ ] getOutputJSON

component
- [ ] getComponentList
- [ ] getComponentInfo
- [ ] createComponent
- [ ] createComponentNewVersion
- [ ] updateComponent

runHistory
- [ ] getPipelineRunHistoryList
- [ ] getPipelineRunHistoryInfo
- [ ] getComponentRunHistoryList
- [ ] getComponentRunHistoryInfo

pipeline part api must finish before Otc. 18
runHistory json struct must finish before Otc. 19
startStage&component api must finish before Otc. 20
